version: 2

updates:
  - package-ecosystem: 'composer'
    directory: '/dev-tools'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    reviewers:
      - 'kubawerlos'
    versioning-strategy: 'increase'
