git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

language: php

notifications:
    email: false

matrix:
    include:
        - php: '7.1'
          env: COMPOSER_FLAGS='--prefer-lowest'
        - php: '7.1'
        - php: '7.2'
        - php: '7.3'
        - php: '7.4snapshot'
          env: COMPOSER_FLAGS="--ignore-platform-reqs" PHP_CS_FIXER_IGNORE_ENV=1

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - composer global outdated --strict hirak/prestissimo || composer global require hirak/prestissimo

install: composer update $COMPOSER_FLAGS

script: composer verify
