git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

language: php

notifications:
    email: false

matrix:
    include:
        - php: '7.0'
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
        - php: '7.0'
        - php: '7.1'
        - php: 'nightly'

before_install:
    - (phpenv config-rm xdebug.ini || exit 0)
    - composer self-update

install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer $COMPOSER_FLAGS

script:
    - vendor/bin/phpcs --ignore=ClassInTheSameFileWithTrait.php --report-full --standard=PSR2 ./src ./tests --ignore=./tests/_stubs
    - ./types-checker --skip-return-types src
    - phpdbg -qrr vendor/bin/phpunit -c tests/phpunit.xml
