#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$application = new Symfony\Component\Console\Application();
$command = new TypesChecker\Command\CheckCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
