name: CI

on:
  - pull_request
  - push

jobs:
  analyse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - run: composer update --no-progress
      - run: composer analyse

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            description: 'with lowest dependencies'
            php-version: '7.2'
            composer_flags: '--prefer-lowest'
          - os: ubuntu-latest
            php-version: '7.2'
          - os: ubuntu-latest
            php-version: '7.3'
          - os: ubuntu-latest
            php-version: '8.0'
          - os: ubuntu-latest
            php-version: '8.1'
          - os: ubuntu-latest
            php-version: '8.2'
            calculate-coverage: true
            phpunit-flags: '--coverage-clover=./build/logs/clover.xml'
          - os: macos-latest
            description: 'on macOS'
            php-version: '8.2'
          - os: windows-latest
            description: 'on Windows'
            php-version: '8.2'
          - os: ubuntu-latest
            php-version: '8.3'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: pcov.directory=$GITHUB_WORKSPACE
          coverage: ${{ (matrix.calculate-coverage && 'pcov') || 'none' }}

      - name: Get Composer data directory
        id: composer-data
        run: echo '::set-output name=dir::$(composer config data-dir)'

      - name: Cache Composer data
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-data.outputs.dir }}
          key: ${{ runner.os }}-composer-data-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-data-

      - name: Get Composer cache directory
        id: composer-cache
        run: echo '::set-output name=dir::$(composer config cache-files-dir)'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Install dependencies
        run: composer update --no-progress ${{ matrix.composer_flags }}

      - name: Run tests
      - run: ./vendor/bin/phpunit ${{ matrix.phpunit-flags }}

      - name: Upload coverage results to Coveralls
        if: ${{ matrix.calculate-coverage }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require --dev php-coveralls/php-coveralls --quiet
          ./vendor/bin/php-coveralls --verbose
